/* eslint-disable @typescript-eslint/no-explicit-any */
import * as AwsIcons from 'aws-react-icons';
import { RefreshCw, MapPin } from 'lucide-react';

const iconComponents: Record<string, any> = {
  region: (AwsIcons as any).ArchitectureGroupAWSRegion,
  ec2: (AwsIcons as any).ArchitectureServiceAmazonEC2,
  lambda: (AwsIcons as any).ArchitectureServiceAWSLambda,
  ecs: (AwsIcons as any).ArchitectureServiceAmazonECSAnywhere,
  eks: (AwsIcons as any).ArchitectureServiceAmazonEKSCloud,
  s3: (AwsIcons as any).ArchitectureServiceAmazonSimpleStorageService,
  ebs: (AwsIcons as any).ArchitectureServiceAmazonElasticBlockStore,
  efs: (AwsIcons as any).ResourceAmazonElasticFileSystemEFSOneZone,
  rds: (AwsIcons as any).ArchitectureServiceAmazonRDS,
  dynamodb: (AwsIcons as any).ArchitectureServiceAmazonDynamoDB,
  elasticache: (AwsIcons as any).ArchitectureServiceAmazonElastiCache,
  vpc: (AwsIcons as any).ArchitectureGroupVirtualprivatecloudVPC,
  subnet: (AwsIcons as any).ArchitectureGroupVirtualprivatecloudVPC,
  elb: (AwsIcons as any).ArchitectureServiceElasticLoadBalancing,
  alb: (AwsIcons as any).ArchitectureServiceElasticLoadBalancing,
  nlb: (AwsIcons as any).ArchitectureServiceElasticLoadBalancing,
  cloudfront: (AwsIcons as any).ArchitectureServiceAmazonCloudFront,
  apigateway: (AwsIcons as any).ArchitectureServiceAmazonAPIGateway,
  iam: (AwsIcons as any).ArchitectureServiceAWSIdentityandAccessManagement,
  iamrole: (AwsIcons as any).ArchitectureServiceAWSIdentityandAccessManagement,
  cognito: (AwsIcons as any).ArchitectureServiceAmazonCognito,
  waf: (AwsIcons as any).ArchitectureServiceAWSWAF,
  shield: (AwsIcons as any).ArchitectureServiceAWSShield,
  cloudwatch: (AwsIcons as any).ArchitectureServiceAmazonCloudWatch,
  cloudtrail: (AwsIcons as any).ArchitectureServiceAWSCloudTrail,
  awsconfig: (AwsIcons as any).ArchitectureServiceAWSConfig,
  awsbackup: (AwsIcons as any).ArchitectureServiceAWSBackup,
  kinesis: (AwsIcons as any).ArchitectureServiceAmazonKinesis,
  'kinesis-streams': (AwsIcons as any).ArchitectureServiceAmazonKinesis,
  firehose: (AwsIcons as any).ArchitectureServiceAmazonKinesisDataFirehose,
  'kinesis-firehose': (AwsIcons as any).ArchitectureServiceAmazonKinesisDataFirehose,
  sqs: (AwsIcons as any).ArchitectureServiceAmazonSimpleQueueService,
  sns: (AwsIcons as any).ArchitectureServiceAmazonSimpleNotificationService,
  eventbridge: (AwsIcons as any).ArchitectureServiceAmazonEventBridge,
  autoscaling: (AwsIcons as any).ArchitectureServiceAutoScaling || RefreshCw,
  'availability-zone': (AwsIcons as any).ArchitectureGroupAWSRegion || MapPin,
  fargate: (AwsIcons as any).ArchitectureServiceAWSFargate,
  elasticbeanstalk: (AwsIcons as any).ArchitectureServiceAWSElasticBeanstalk,
  glacier: (AwsIcons as any).ArchitectureServiceAmazonS3Glacier,
  aurora: (AwsIcons as any).ArchitectureServiceAmazonAuroraMySQL,
  redshift: (AwsIcons as any).ArchitectureServiceAmazonRedshift,
  securitygroup: (AwsIcons as any).ArchitectureGroupVirtualprivatecloudVPC,
  networkacl: (AwsIcons as any).ArchitectureGroupVirtualprivatecloudVPC,
  internetgateway: (AwsIcons as any).ArchitectureGroupInternetGateway,
  natgateway: (AwsIcons as any).ArchitectureGroupVirtualprivatecloudVPC,
  route53: (AwsIcons as any).ArchitectureServiceAmazonRoute53,
  vpcpeering: (AwsIcons as any).ArchitectureGroupVirtualprivatecloudVPC,
  transitgateway: (AwsIcons as any).ArchitectureGroupVirtualprivatecloudVPC,
  awsorganizations: (AwsIcons as any).ArchitectureServiceAWSOrganizations,
  secretsmanager: (AwsIcons as any).ArchitectureServiceAWSSecretsManager,
  ssmparameterstore: (AwsIcons as any).ArchitectureServiceAWSSystemsManagerParameterStore,
  cloudformation: (AwsIcons as any).ArchitectureServiceAWSCloudFormation,
  awscdk: (AwsIcons as any).ArchitectureServiceAWSCloudFormation,
  codepipeline: (AwsIcons as any).ArchitectureServiceAWSCodePipeline,
  codebuild: (AwsIcons as any).ArchitectureServiceAWSCodeBuild,
  codedeploy: (AwsIcons as any).ArchitectureServiceAWSCodeDeploy,
  athena: (AwsIcons as any).ArchitectureServiceAmazonAthena,
};

export const getIconComponent = (iconId: string): any => {
  return iconComponents[iconId] || null;
};
